[font]
size = 18.0

[font.normal]
family = "SF Mono"
style = "Regular"

[font.bold]
family = "SF Mono"
style = "Regular"

[window]
padding = { x = 4, y = 5 }
decorations = "full"

[colors.normal]
black = "0x282c34"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xe5c07b"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xabb2bf"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xe5c07b"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xffffff"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "Always"
