#!/bin/zsh

if ! command -v fzf &>/dev/null; then
    echo "Installing fzf..."
    brew install fzf
else
    echo "fzf is already installed."
fi

# Run the install script provided by fzf
echo "Setting up fzf key bindings and auto-completion..."
$(brew --prefix)/opt/fzf/install

echo "fzf installation and setup complete."
